name: CI_build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maintained_windows_x64:

    runs-on: windows-2022
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Build maintained x64 Release package
      shell: cmd
      run: build.bat -Arch x64 -Config Release

    - name: Archive maintained x64 package
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
          name: NppFTP-maintained-win64
          path: |
            _build\NppFTP-0.30.22-win64.zip
            _build\Release\NppFTP.dll
